// Optional authoring interchange: export the exact procedural scene as GLB 2.0.
// Not loaded by the portable app. Open in a glTF-compatible 3D authoring tool.
const fs=require('fs'),vm=require('vm'),path=require('path');
for(const p of ['instrumentation-plans.js','campus-v8.js','architecture-v10.js'])vm.runInThisContext(fs.readFileSync(path.join(__dirname,p),'utf8'));
function exportGLB(data,name){let json={asset:{version:'2.0',generator:'Metari Architecture Studio v10'},scene:0,scenes:[{nodes:[]}],nodes:[],meshes:[],materials:[],buffers:[{byteLength:0}],bufferViews:[],accessors:[]},parts=[],offset=0;
 const append=(buf,target)=>{let padded=Buffer.alloc(Math.ceil(buf.length/4)*4);buf.copy(padded);let i=json.bufferViews.length;json.bufferViews.push({buffer:0,byteOffset:offset,byteLength:buf.length,...(target?{target}: {})});parts.push(padded);offset+=padded.length;return i;};
 const accessor=(arr,size,type,min,max)=>{const id=json.accessors.length,buf=Buffer.from(new Float32Array(arr).buffer);let b=append(buf,34962);json.accessors.push({bufferView:b,componentType:5126,count:arr.length/size,type,...(min?{min,max}:{})});return id;};
 const groups=new Map();for(const ar of [data.opaque,data.glass])for(let i=0;i<ar.length;i+=54){let fl=ar[i+12],type=ar[i+9],part=ar[i+13];if(part===3||part===4||part===5)continue;let key=[fl,type,ar[i+15]].join('_');if(!groups.has(key))groups.set(key,{fl,type,alpha:ar[i+15],rough:ar[i+10],metal:ar[i+11],pos:[],nor:[],col:[],uv:[]});let g=groups.get(key);for(let j=0;j<3;j++){let k=i+j*18;g.pos.push(...ar.slice(k,k+3));g.nor.push(...ar.slice(k+3,k+6));g.col.push(...Array.from(ar.slice(k+6,k+9),x=>Math.pow(x,2.2)));g.uv.push(ar[k+16],1-ar[k+17]);}}
 let floorNodes={};for(let f of [...new Set([...groups.values()].map(g=>g.fl))].sort((a,b)=>a-b)){floorNodes[f]=json.nodes.length;json.scenes[0].nodes.push(json.nodes.length);json.nodes.push({name:f<0?(name.includes('Showroom')?'Showroom':'Grounds'):f===3?'Roof assembly — not occupied':'Level '+(f+1),translation:[0,f<0?0:f*4.2,0],children:[],extras:{conceptual:true,occupiedFloor:f>=0&&f<3}});}
 let logo=fs.readFileSync(path.join(__dirname,'assets/logo-horizontal.png'));let imageView=append(logo);json.images=[{bufferView:imageView,mimeType:'image/png'}];json.samplers=[{magFilter:9729,minFilter:9729,wrapS:33071,wrapT:33071}];json.textures=[{sampler:0,source:0}];
 for(const g of groups.values()){let min=[Infinity,Infinity,Infinity],max=[-Infinity,-Infinity,-Infinity];for(let i=0;i<g.pos.length;i++)min[i%3]=Math.min(min[i%3],g.pos[i]),max[i%3]=Math.max(max[i%3],g.pos[i]);let pbr={baseColorFactor:[1,1,1,g.alpha],metallicFactor:g.metal,roughnessFactor:g.rough};if(g.type===9)pbr.baseColorTexture={index:0};let mi=json.materials.length;json.materials.push({name:'Material '+g.type,pbrMetallicRoughness:pbr,doubleSided:true,alphaMode:g.alpha<1||g.type===9?'BLEND':'OPAQUE',...(g.type===8?{emissiveFactor:[.6,.3,.1]}:{})});let mesh=json.meshes.length;json.meshes.push({primitives:[{attributes:{POSITION:accessor(g.pos,3,'VEC3',min,max),NORMAL:accessor(g.nor,3,'VEC3'),COLOR_0:accessor(g.col,3,'VEC3'),TEXCOORD_0:accessor(g.uv,2,'VEC2')},material:mi,mode:4}]});let ni=json.nodes.length;json.nodes.push({name:'Floor '+g.fl+' / material '+g.type,mesh});json.nodes[floorNodes[g.fl]].children.push(ni);}
 json.buffers[0].byteLength=offset;json.extras={disclaimer:'Concept geometry and generic robot forms; not a scanned property or validated hardware. Exact Metari artwork supplied by user. Dynamic heatmaps omitted.',floorSeparation:'Translate complete Level 2 and Level 3 nodes upward; never scale assemblies.'};let jb=Buffer.from(JSON.stringify(json)),jpad=Buffer.alloc(Math.ceil(jb.length/4)*4,32);jb.copy(jpad);let bin=Buffer.concat(parts),head=Buffer.alloc(12);head.writeUInt32LE(0x46546c67,0);head.writeUInt32LE(2,4);head.writeUInt32LE(12+8+jpad.length+8+bin.length,8);let jh=Buffer.alloc(8);jh.writeUInt32LE(jpad.length,0);jh.writeUInt32LE(0x4e4f534a,4);let bh=Buffer.alloc(8);bh.writeUInt32LE(bin.length,0);bh.writeUInt32LE(0x004e4942,4);fs.mkdirSync(path.join(__dirname,'models'),{recursive:true});fs.writeFileSync(path.join(__dirname,'models',name),Buffer.concat([head,jh,jpad,bh,bin]));console.log(name,bin.length,'binary bytes',json.meshes.length,'meshes');}
exportGLB(MetariArchitecture.campusModel(),'Metari_Campus_3D.glb');exportGLB(MetariArchitecture.showroomModel(),'Metari_Showroom_3D.glb');
