// v10 integrates the real WebGL scene into the existing app closure.
const v10={selected:null};
Object.assign(v8.campus,{yaw:-.23,pitch:.60,spread:.85,cutaway:true,heat:false,zoom:1});
Object.assign(v8.showroom,{yaw:.22,pitch:.24,heat:false,zoom:1});
function v10Dock(){const r=window.MetariArchitecture.ROOMS.find(r=>r.id===v10.selected);return r?`<div class="v10-selected-card"><div><span>SELECTED SPACE / ${r.floor<0?'GROUNDS':'LEVEL '+String(r.floor+1).padStart(2,'0')}</span><h3>${esc(r.label)}</h3><p>${r.id==='showroom'?'Buyer discovery, comparisons and evaluation planning.':esc(env(r.id).tasks.slice(0,2).join(' · '))}</p></div><div class="flex wrap">${btn('Focus in 3D','v10Focus',r.id,'secondary small','target')}${r.id==='showroom'?btn('Enter showroom','nav','showroom','primary small','arrow'):btn('Open rooms','v8Room',r.id,'primary small','arrow')+btn('Camera layout','studioOpen',r.id+'|'+env(r.id).captureSpace,'secondary small','camera')}</div></div>`:`<div class="v10-empty-selection"><span>${I('target')} SELECT A SPACE</span><p>Click a room label or a modeled room. Its records and camera plans stay connected.</p></div>`;}
function v10Select(id){v10.selected=id;v8.campus.selected=id;for(const [host,r] of v8Scenes)if(host.dataset.v8Scene==='campus')r.update({selected:id});document.querySelectorAll('[data-v10-dock]').forEach(n=>n.innerHTML=v10Dock());}
function v8CampusWidget(key='home'){return `<section class="panel v5-map-panel v10-campus-panel"><div class="v10-scene-heading"><div><span class="v10-eyebrow">METARI / SPATIAL INTELLIGENCE</span><h2>The campus, brought to life.</h2><p>Three occupied floors. One continuous learning loop.</p></div><span class="v10-engine-chip"><i></i> REAL-TIME 3D <small>CONCEPT</small></span></div>
<div class="v10-primary-tools"><div class="v10-tabset">${v8Button('Campus','v10Mode','campus',!v8.campus.cutaway,'box')}${v8Button('Intelligence','v10Mode','intelligence',v8.campus.cutaway,'layers')}</div><div class="v10-toolbar-right">${v8Button('Play reveal','v10Intro','',false,'play')}${btn('Expand','v5Expand','','ghost small','expand')}</div></div>
<div class="v8-floor-tabs" role="group" aria-label="Choose a building floor">${[['all','Whole campus'],['2','03 · Living'],['1','02 · Experience'],['0','01 · Operations'],['outdoor','Grounds']].map(([id,n])=>v8Button(n,'v8Floor',id,String(v8.campus.floor)===id)).join('')}</div>
<div class="v8-scene v8-campus-scene v10-campus-scene" data-v8-scene="campus" data-scene-key="${key}"><canvas tabindex="0" aria-label="Real 3D conceptual campus. Drag to orbit; shift-drag or right-drag to pan. Scroll or pinch to zoom. Click a room to select it."></canvas><div class="v8-scene-labels"></div><div class="v10-loading"><span></span>Preparing architectural scene…</div><div class="v10-corner-mark">WEST CAMPUS <small>Concept geometry · simulated data</small></div><div class="v8-scene-help">Drag to orbit <span>·</span> Shift-drag to pan <span>·</span> Scroll or pinch to zoom</div></div>
<div class="v10-selected-host" data-v10-dock>${v10Dock()}</div>
<div class="v10-control-deck"><div class="v8-view-tools"><div class="v8-control-group">${v8Button('Orbit','v8Pan','orbit',!v8.pan,'globe')}${v8Button('Pan','v8Pan','pan',v8.pan,'move')}${v8Button('Top','v8View','top',false,'layers')}${v8Button('Isometric','v8View','iso',false,'box')}${v8Button('Turntable','v8View','rotate',v8.campus.rotate,'loop')}</div><div class="v8-control-group">${ibtn('Rotate left','v8View','left','chevron')}${ibtn('Rotate right','v8View','right','arrow')}${ibtn('Zoom out','v8Zoom','out','minus')}${ibtn('Zoom in','v8Zoom','in','plus')}${ibtn('Reset campus view','v8View','reset','target')}</div></div>
<div class="v8-floor-spacing"><label>Floor separation<input type="range" min="0" max="100" value="${Math.round(v8.campus.spread*100)}" data-v8-spacing aria-label="Floor separation"></label><span data-v8-spread-value>${Math.round(v8.campus.spread*100)}%</span>${v8Button('Assemble','v8Spread','0',v8.campus.spread===0)}${v8Button('Explode','v8Spread','1',v8.campus.spread===1)}</div>
<div class="v10-overlay-tools"><span>DATA LAYER</span>${v8Button(v8.campus.heat?'Heat on':'Heat off','v10Heat','',v8.campus.heat,'waves')}<select data-v10-layer aria-label="3D overlay mode">${options([{id:'thermal',name:'Thermal · simulated'},{id:'activity',name:'Activity · simulated'},{id:'coverage',name:'Seeded coverage'},{id:'gaps',name:'Collection gaps'}],v5UI.mode)}</select>${v8Button('Labels','v8Labels','',v8.campus.labels,'book')}${v8Button('Cameras','v5MapCameras','',v5UI.cameras,'camera')}${v8Button('Task paths','v5MapPaths','',v5UI.paths,'route')}</div>
<div class="v8-clock-strip">${v8Button(v5UI.playing?'Pause sample':'Play sample','v5Play','',v5UI.playing,v5UI.playing?'pause':'play')}<input type="range" min="0" max="28" value="${v5UI.slot}" data-v5-time aria-label="Property sample time"><span class="v5-time-label">${v5TimeLabel()}</span></div></div>
<details class="v8-room-directory"><summary>Explore every environment <span>20 environments + experience center</span></summary><div>${window.MetariArchitecture.ROOMS.map(r=>`<button data-action="v8Room" data-id="${r.id}"><span>${r.floor<0?'G':String(r.floor+1).padStart(2,'0')}</span>${r.label}${I('arrow','small')}</button>`).join('')}</div></details>
<div class="v8-campus-callout">${I('box')}<span><b>From discovery to an evidence-led pilot.</b> Explore systems inside a furnished architectural showroom.</span>${btn('Enter showroom','nav','showroom','primary small','arrow')}</div></section>`;}
// Mount a genuine 3D renderer; retain all original app models, comparisons and planning logic.
function v8Mount(){for(const [host,r] of v8Scenes){if(!host.isConnected||host.closest('dialog')&&!host.closest('dialog').open){r.destroy();v8Scenes.delete(host);}}document.querySelectorAll('[data-v8-scene]').forEach(host=>{if(host.closest('dialog')&&!host.closest('dialog').open)return;if(v8Scenes.has(host)){v8Scenes.get(host).refresh();return;}const kind=host.dataset.v8Scene,key=host.dataset.modelId;const view=kind==='campus'?v8.campus:key?{yaw:.1,pitch:.16,zoom:1.12,labels:false,focusModel:key,heat:false,rotate:false}:v8.showroom;try{const r=window.MetariArchitecture.makeRenderer(host,{type:kind==='campus'?'campus':'showroom',view,panMode:()=>v8.pan,data:()=>({state,selected:v8.selected,paused:v8Paused()||!!($('#modal').open&&!host.closest('dialog')),mode:v5UI.mode,cameras:v5UI.cameras,paths:v5UI.paths,intensity:id=>id==='showroom'?.5:V5.intensity(state,id,v5UI.mode,v5UI.slot)}),onPick:id=>{if(kind==='campus')v10Select(id);else{v8.selected=id;if(!key)v8UpdateSelection();}}});v8Scenes.set(host,r);}catch(e){console.error(e);host.insertAdjacentHTML('beforeend','<div class="v10-context-lost">3D could not initialize. Room directory and other workflows remain available.</div>');}});v10Controls();}
function v10Controls(){document.querySelectorAll('[data-action="v10Mode"]').forEach(b=>{let on=(b.dataset.id==='intelligence')===v8.campus.cutaway;b.classList.toggle('selected',on);b.setAttribute('aria-pressed',on)});document.querySelectorAll('[data-action="v8Floor"]').forEach(b=>{let on=b.dataset.id===String(v8.campus.floor);b.classList.toggle('selected',on);b.setAttribute('aria-pressed',on)});document.querySelectorAll('[data-action="v8Labels"]').forEach(b=>{b.classList.toggle('selected',v8.campus.labels);b.setAttribute('aria-pressed',v8.campus.labels)});document.querySelectorAll('[data-action="v8Pan"]').forEach(b=>{let on=(b.dataset.id==='pan')===v8.pan;b.classList.toggle('selected',on);b.setAttribute('aria-pressed',on)});document.querySelectorAll('[data-action="v8Spread"]').forEach(b=>{let on=Number(b.dataset.id)===v8.campus.spread;b.classList.toggle('selected',on);b.setAttribute('aria-pressed',on)});document.querySelectorAll('[data-action="v10Heat"]').forEach(b=>{b.classList.toggle('selected',v8.campus.heat);b.setAttribute('aria-pressed',v8.campus.heat);b.innerHTML=I('waves','small')+(v8.campus.heat?'Heat on':'Heat off');});document.querySelectorAll('[data-v8-spacing]').forEach(n=>n.value=Math.round(v8.campus.spread*100));document.querySelectorAll('[data-v8-spread-value]').forEach(n=>n.textContent=Math.round(v8.campus.spread*100)+'%');}
const originalV8Action=v8Action;
v8Action=function(name,id,el){let handled=true;switch(name){case 'v10Mode':v8SceneUpdate('campus',{cutaway:id==='intelligence',spread:id==='campus'?0:.85,floor:'all',panX:0,panY:0,zoom:1});break;case 'v10Heat':v8SceneUpdate('campus',{heat:!v8.campus.heat});break;case 'v10Focus':for(const [host,r]of v8Scenes)if(host.dataset.v8Scene==='campus')r.focusRoom?.(id);break;case 'v10Intro':if(v8Paused()){toast('Motion is paused. Manual controls remain available.');break;}for(const [host,r]of v8Scenes)if(host.dataset.v8Scene==='campus')r.startIntro?.();toast('Reveal started. Drag the scene or use any view control to interrupt.');break;case 'v8Floor':v8SceneUpdate('campus',{floor:['all','outdoor'].includes(id)?id:Number(id),cutaway:true,zoom:1});break;case 'v8Spread':v8SceneUpdate('campus',{spread:Number(id),cutaway:true,floor:'all'});break;case 'v8Pan':v8.pan=id==='pan';break;case 'v8Labels':v8SceneUpdate('campus',{labels:!v8.campus.labels});break;case 'v8View':if(id==='reset'){v10.selected=null;v8SceneUpdate('campus',{yaw:-.23,pitch:.60,zoom:1,panX:0,panY:0,floor:'all',spread:.85,rotate:false,labels:true,cutaway:true,heat:false});document.querySelectorAll('[data-v10-dock]').forEach(n=>n.innerHTML=v10Dock());}else if(id==='top')v8SceneUpdate('campus',{pitch:1.5,yaw:0,zoom:1,panX:0,panY:0});else if(id==='iso')v8SceneUpdate('campus',{pitch:.73,yaw:-.23,zoom:1,panX:0,panY:0});else if(id==='left'||id==='right')v8SceneUpdate('campus',{yaw:v8.campus.yaw+(id==='right'?.22:-.22),rotate:false});else if(id==='rotate'){if(v8Paused()){toast('Motion is paused.');break;}v8SceneUpdate('campus',{rotate:!v8.campus.rotate});el?.classList.toggle('selected',v8.campus.rotate);}break;default:handled=false;}if(handled){v10Controls();return true;}return originalV8Action(name,id,el);};
const originalV5Action=v5Action;
v5Action=function(name,id,el){if(name==='v5MapCameras'||name==='v5MapPaths'){const k=name==='v5MapCameras'?'cameras':'paths';v5UI[k]=!v5UI[k];document.querySelectorAll(`[data-action="${name}"]`).forEach(b=>{b.classList.toggle('selected',v5UI[k]);b.setAttribute('aria-pressed',v5UI[k]);});v8CampusRefresh();return true;}return originalV5Action(name,id,el);};
document.addEventListener('change',e=>{if(e.target.matches('[data-v10-layer]')){v5UI.mode=e.target.value;v8SceneUpdate('campus',{heat:true});v8CampusRefresh();v10Controls();}});
// The furnished showroom is the default architectural experience; approved photography remains adjacent as a reference.
const originalShowroom=showroom;
showroom=function(){let s=originalShowroom();const begin=s.indexOf('<section class="v9-showroom-photo-grid">'),end=s.indexOf('<section class="panel v8-showroom-hero">');if(begin>=0&&end>begin){const photos=s.slice(begin,end);s=s.slice(0,begin)+s.slice(end);const i=s.indexOf('<div class="v8-gallery-filters"');s=s.slice(0,i)+`<details class="v10-reference-photos"><summary>Approved experience-center photography <span>Concept art / visual reference</span></summary>${photos}</details>`+s.slice(i);}s=s.replace('HUMANOID GALLERY','ARCHITECTURAL SHOWROOM').replace('Click a concept. Orbit the gallery. Inspect before you decide.','Explore the room. Click a display. Compare concepts and plan an evaluation.');return s;};
